# Generated by Django 2.2.3 on 2019-07-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
