# Generated by Django 2.2.3 on 2019-07-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20190703_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='interface.User'),
            preserve_default=False,
        ),
    ]
